In [1]:
import torch 
import torch.nn as nn


In [7]:
inputs = torch.Tensor([[[0.2, 0.1, 0.3], [0.5, 0.1, 0.1]]])
B,S,E = inputs.size()
inputs = inputs.reshape(S,B,E)
inputs.size()

torch.Size([2, 1, 3])

In [9]:
paramater_shape = inputs.size()[-2:]
gamma = nn.Parameter(torch.ones(paramater_shape))
beta = nn.Parameter(torch.zeros(paramater_shape))

In [10]:
gamma.size(), beta.size()

(torch.Size([1, 3]), torch.Size([1, 3]))

In [11]:
dims = [-(i+1) for i in range(len(paramater_shape))]
dims 

[-1, -2]

In [13]:
mean = inputs.mean(dim=dims, keepdim=True)
mean.size()

torch.Size([2, 1, 1])

In [14]:
mean

tensor([[[0.2000]],

        [[0.2333]]])

In [16]:
var = ((inputs-mean)**2).mean(dim=dims, keepdim=True)
epsilon = 1e-5
std = (var + epsilon).sqrt()
std

tensor([[[0.0817]],

        [[0.1886]]])

In [18]:
y = (inputs- mean) / std
y

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]])

In [19]:
out = gamma*y + beta

In [20]:
out

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]], grad_fn=<AddBackward0>)

All in one

In [22]:
import torch
import torch.nn


class LayerNormalization():
    def __init__(self,paramater_shape,eps=1e-5):
        self.paramater_shape = paramater_shape
        self.eps = eps
        self.gamma = nn.Parameter(torch.ones(self.paramater_shape))
        self.beta = nn.Parameter(torch.zeros(self.paramater_shape))

    def forward(self, input):
        dims = [-(i+1) for i in range(len(self.paramater_shape))]
        mean = inputs.mean(dim=dims, keepdim=True)
        var = ((inputs-mean)**2).mean(dim=dims, keepdim=True)
        std = (var + self.eps).sqrt()
        y = (inputs- mean) / std
        out = self.gamma * y + self.beta
        return out
        


In [23]:
batch_size = 3
sentence_length = 5
embeding_dim = 8
inputs = torch.randn(sentence_length,batch_size,embeding_dim )

In [26]:
layer_norm = LayerNormalization(inputs.size()[-2:])
layer_norm


In [27]:
out = layer_norm.forward(inputs)
out 

tensor([[[-0.0947,  1.7079, -0.2363,  0.7305,  0.1923, -0.9733,  0.2513,
           1.2618],
         [-2.0164, -0.9688, -0.8756,  0.3777,  1.2298,  0.3281, -1.8530,
          -0.4741],
         [ 0.5918, -1.5766,  1.1257, -0.0783,  0.0078,  1.2750, -0.6430,
           0.7102]],

        [[-2.1341, -0.0640, -0.0089,  2.0548, -1.1545,  0.4335, -0.9735,
           1.1495],
         [-1.2128,  0.0338,  0.0108, -0.9864,  0.4896,  0.3573,  2.0161,
          -0.2711],
         [-0.1313,  1.1666,  1.2473, -1.0486, -0.3716, -0.4773, -0.2515,
           0.1266]],

        [[-0.4260,  0.7262,  0.2152, -0.8853, -1.0732,  1.0433,  1.0721,
          -1.6118],
         [ 0.1746,  0.9773, -0.5086,  1.8274, -2.2110, -0.2582,  0.9993,
          -0.9094],
         [ 0.7946, -0.5698, -0.3567,  1.6843, -0.1202, -0.4495, -0.7610,
           0.6265]],

        [[-1.5895, -0.2509, -0.8111, -1.0666,  1.0842, -0.4421,  0.1551,
           0.1723],
         [-1.3493,  0.4756, -0.6310, -0.4713,  1.7378,  1.1825, 